### PR TITLE
Cumulative update

### PR DESCRIPTION
**Pull request by un-def**
- Update both C and Lua code for Lua 5.2/5.3 compatibility;
- Add some input value checks;
- Fix some bugs;
- Optimizations;
- Tests;
- rockspec file for installation with luarocks;
- Travis CI.

### CODE REVIEW

**Comment by leihog** [comment]
I would appreciate it if you could split the PR in to multiple smaller ones, each containing only one commit (squash them) fixing only one issue. It's hard to get an overview of the changes as it is now and the PR includes things that aren't really relevant outside your fork. 
If you prefer I can just cherry-pick the relevant changes myself.

As for the luarocks parts, I agree that hashids.lua should be on luarocks.
What I am less inclined to agree with is that it's your fork that is on luarocks.

**Comment by un-def** [comment]
It's difficult now to split and squash commits according to issues they fixes so I prefer cherry-pick solution.

LuaRocks module can be easily replaced, I can delete my module or maintain your rockspec file.

**Comment by leihog** [comment]
Just wanted to let you know that I haven't forgotten about you.
I've had a busy week so haven't gotten around to this yet.
I'll cherry-pick the commits merge them with you as Author.
I'll also add a credit section in which your contribution will be mentioned.
I'd appreciate it if you would also remove your fork from luarocks upon which I'll submit my version.

Thank you btw. :)

**Comment by un-def** [comment]
I've deleted my hashids luarocks module.

https://luarocks.org/search?q=hashids

**Pull request closed without merging**
